jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Jest with Coverage
          command: npm test
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage
